In [32]:
import pandas as pd
import numpy as np

In [48]:
dados = pd.read_excel(r'C:\Users\gabriel.coimbra\Desktop\Meus arquivos\Tapes\Resultados Analíticos ETE Tapes (1).xlsx', skiprows=8, decimal = ',')

In [49]:
dados = dados.dropna(axis=1, how='all')
dados.columns = dados.columns.str.replace('\n', ' ', regex=False)
dados = dados.drop(index=32)

In [50]:
dados

,AMOSTRA,DATA,HORA,OBS,Ponto,Ident. Componente,DBO5 mg O2/L,DQO mg O2/L,Ecoli NMP/100mL,NNH3 mg N/L,P tot mg P/L,pH,SST mg/L,T_Amb ºC,T_Am ºC,T_Receb °C,T_Receb ºC
0,890DECTE,20/01/2025,08:30,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,ND,3.66,NaN,NaN,24.0,25.0,NaN,19.0
1,892DECTE,20/01/2025,08:30,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),30.2,708.0,20.0,NaN,NaN,7.6,180.0,24.0,25.0,NaN,19.0
2,889DECTE,20/01/2025,08:40,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,17.3,2.70,NaN,NaN,24.0,26.0,NaN,19.0
3,891DECTE,20/01/2025,08:40,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),52.0,225.0,3873000.0,NaN,NaN,6.7,90.0,24.0,26.0,NaN,19.0
4,3510DECTE,17/02/2025,10:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),29.8,515.0,100.0,NaN,NaN,8.4,150.0,24.0,26.0,16.7,NaN
5,3506DECTE,17/02/2025,10:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.85,2.68,NaN,NaN,24.0,26.0,16.7,NaN
6,3505DECTE,17/02/2025,11:10,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,14.6,2.29,NaN,NaN,24.0,25.0,16.7,NaN
7,3509DECTE,17/02/2025,11:10,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),"<9,9",129.0,1396000.0,NaN,NaN,7.3,32.0,24.0,25.0,16.7,NaN
8,5205DECTE,17/03/2025,09:05,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),58.4,673.0,1.0,NaN,NaN,8.1,271.0,24.0,21.0,NaN,15.0
9,5201DECTE,17/03/2025,09:05,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,"<0,76",2.08,NaN,NaN,24.0,21.0,NaN,15.0
10,5200DECTE,17/03/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,53.4,7.56,NaN,NaN,24.0,20.0,NaN,15.0
11,5204DECTE,17/03/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),93.0,266.0,7030000.0,NaN,NaN,7.7,130.0,24.0,20.0,NaN,15.0
12,7294DECTE,14/04/2025,09:20,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),43.5,672.0,1.0,NaN,NaN,9.9,308.0,20.0,21.0,NaN,14.0
13,7292DECTE,14/04/2025,09:20,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,1.19,2.85,NaN,NaN,20.0,21.0,13.7,NaN
14,7293DECTE,14/04/2025,09:50,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),120,337.0,6630000.0,NaN,NaN,7.1,90.0,20.0,20.0,NaN,14.0
15,7291DECTE,14/04/2025,09:50,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,80.7,7.98,NaN,NaN,20.0,20.0,13.7,NaN
16,8133DECTE,19/05/2025,00:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),8.71,86.0,110.0,NaN,NaN,8.8,18.0,20.0,19.0,NaN,19.0
17,8131DECTE,19/05/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,3.69,1.66,NaN,NaN,20.0,19.0,NaN,19.0
18,8130DECTE,19/05/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,72.1,7.68,NaN,NaN,20.0,20.0,NaN,19.0
19,8132DECTE,19/05/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),140,430.0,5830000.0,NaN,NaN,7.3,102.0,20.0,20.0,NaN,19.0
20,9550DECTE,10/06/2025,04:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,"<0,76",1.21,NaN,NaN,10.0,11.0,NaN,8.0
21,9552DECTE,10/06/2025,08:44,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),7.50,93.6,40.0,NaN,NaN,7.9,46.0,10.0,11.0,NaN,16.0
22,9551DECTE,10/06/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),85.0,448.0,6867000.0,NaN,NaN,7.1,110.0,10.0,14.0,NaN,16.0
23,9549DECTE,10/06/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,94.8,7.50,NaN,NaN,10.0,14.0,NaN,8.0
24,11973DECTE,16/07/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,ND,1.28,NaN,NaN,14.0,14.0,NaN,17.0
25,11975DECTE,16/07/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),8.98,82.5,30.0,NaN,NaN,8.4,48.0,14.0,14.0,NaN,17.0
26,11972DECTE,16/07/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,54.5,6.22,NaN,NaN,14.0,16.0,NaN,17.0
27,11974DECTE,16/07/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),71.0,449.0,4884000.0,NaN,NaN,7.4,72.0,14.0,16.0,NaN,17.0
28,13564DECTE,06/08/2025,00:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,NaN,1.25,NaN,NaN,16.0,15.0,NaN,8.0
29,13566DECTE,06/08/2025,09:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),6.30,82.6,20.0,NaN,NaN,8.6,98.0,16.0,15.0,NaN,8.0
30,13563DECTE,06/08/2025,11:08,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,NaN,3.76,NaN,NaN,17.0,16.0,NaN,8.0
31,13565DECTE,06/08/2025,11:08,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),69.0,161.0,82000.0,NaN,NaN,7.2,126.0,17.0,16.0,NaN,8.0

In [66]:
colunas_interesse = ['DBO5 mg O2/L', 'DQO mg O2/L', 'Ecoli NMP/100mL', 'NNH3 mg N/L','P tot mg P/L', 'pH',
                     'SST mg/L', 'T_Amb ºC', 'T_Am ºC', 'T_Receb °C','T_Receb ºC']

for coluna in colunas_interesse:
    dados[coluna] = dados[coluna].astype(str).str.replace('<', '', regex=False)
    dados[coluna] = dados[coluna].str.replace('>', '', regex=False)
    dados[coluna] = dados[coluna].str.replace('ND', '0', regex=False)
    dados[coluna] = dados[coluna].str.strip()
    dados[coluna] = pd.to_numeric(dados[coluna], errors='coerce')

media = dados[colunas_interesse].notna().astype(int).mean()
mediana = dados[colunas_interesse].notna().astype(int).median()

In [68]:
dados

,AMOSTRA,DATA,HORA,OBS,Ponto,Ident. Componente,DBO5 mg O2/L,DQO mg O2/L,Ecoli NMP/100mL,NNH3 mg N/L,P tot mg P/L,pH,SST mg/L,T_Amb ºC,T_Am ºC,T_Receb °C,T_Receb ºC
0,890DECTE,20/01/2025,08:30,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.00,3.66,NaN,NaN,24.0,25.0,NaN,19.0
1,892DECTE,20/01/2025,08:30,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),30.20,708.0,20.0,NaN,NaN,7.6,180.0,24.0,25.0,NaN,19.0
2,889DECTE,20/01/2025,08:40,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,17.30,2.70,NaN,NaN,24.0,26.0,NaN,19.0
3,891DECTE,20/01/2025,08:40,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),52.00,225.0,3873000.0,NaN,NaN,6.7,90.0,24.0,26.0,NaN,19.0
4,3510DECTE,17/02/2025,10:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),29.80,515.0,100.0,NaN,NaN,8.4,150.0,24.0,26.0,16.7,NaN
5,3506DECTE,17/02/2025,10:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.85,2.68,NaN,NaN,24.0,26.0,16.7,NaN
6,3505DECTE,17/02/2025,11:10,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,14.60,2.29,NaN,NaN,24.0,25.0,16.7,NaN
7,3509DECTE,17/02/2025,11:10,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,129.0,1396000.0,NaN,NaN,7.3,32.0,24.0,25.0,16.7,NaN
8,5205DECTE,17/03/2025,09:05,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),58.40,673.0,1.0,NaN,NaN,8.1,271.0,24.0,21.0,NaN,15.0
9,5201DECTE,17/03/2025,09:05,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.00,2.08,NaN,NaN,24.0,21.0,NaN,15.0
10,5200DECTE,17/03/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,53.40,7.56,NaN,NaN,24.0,20.0,NaN,15.0
11,5204DECTE,17/03/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),93.00,266.0,7030000.0,NaN,NaN,7.7,130.0,24.0,20.0,NaN,15.0
12,7294DECTE,14/04/2025,09:20,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),43.50,672.0,1.0,NaN,NaN,9.9,308.0,20.0,21.0,NaN,14.0
13,7292DECTE,14/04/2025,09:20,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,1.19,2.85,NaN,NaN,20.0,21.0,13.7,NaN
14,7293DECTE,14/04/2025,09:50,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),120.00,337.0,6630000.0,NaN,NaN,7.1,90.0,20.0,20.0,NaN,14.0
15,7291DECTE,14/04/2025,09:50,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,80.70,7.98,NaN,NaN,20.0,20.0,13.7,NaN
16,8133DECTE,19/05/2025,00:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),8.71,86.0,110.0,NaN,NaN,8.8,18.0,20.0,19.0,NaN,19.0
17,8131DECTE,19/05/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,3.69,1.66,NaN,NaN,20.0,19.0,NaN,19.0
18,8130DECTE,19/05/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,72.10,7.68,NaN,NaN,20.0,20.0,NaN,19.0
19,8132DECTE,19/05/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),140.00,430.0,5830000.0,NaN,NaN,7.3,102.0,20.0,20.0,NaN,19.0
20,9550DECTE,10/06/2025,04:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.00,1.21,NaN,NaN,10.0,11.0,NaN,8.0
21,9552DECTE,10/06/2025,08:44,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),7.50,93.6,40.0,NaN,NaN,7.9,46.0,10.0,11.0,NaN,16.0
22,9551DECTE,10/06/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),85.00,448.0,6867000.0,NaN,NaN,7.1,110.0,10.0,14.0,NaN,16.0
23,9549DECTE,10/06/2025,09:20,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,94.80,7.50,NaN,NaN,10.0,14.0,NaN,8.0
24,11973DECTE,16/07/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,0.00,1.28,NaN,NaN,14.0,14.0,NaN,17.0
25,11975DECTE,16/07/2025,08:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),8.98,82.5,30.0,NaN,NaN,8.4,48.0,14.0,14.0,NaN,17.0
26,11972DECTE,16/07/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,54.50,6.22,NaN,NaN,14.0,16.0,NaN,17.0
27,11974DECTE,16/07/2025,09:30,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),71.00,449.0,4884000.0,NaN,NaN,7.4,72.0,14.0,16.0,NaN,17.0
28,13564DECTE,06/08/2025,00:00,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,NaN,1.25,NaN,NaN,16.0,15.0,NaN,8.0
29,13566DECTE,06/08/2025,09:50,-,Efluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),6.30,82.6,20.0,NaN,NaN,8.6,98.0,16.0,15.0,NaN,8.0
30,13563DECTE,06/08/2025,11:08,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),NaN,NaN,NaN,NaN,3.76,NaN,NaN,17.0,16.0,NaN,8.0
31,13565DECTE,06/08/2025,11:08,-,Afluente R Mauá nº 1240,ETE Lagoa dos Patos (Tapes),69.00,161.0,82000.0,NaN,NaN,7.2,126.0,17.0,16.0,NaN,8.0

In [55]:
dados[colunas_interesse].notna()

,DBO5 mg O2/L,DQO mg O2/L,Ecoli NMP/100mL,NNH3 mg N/L,P tot mg P/L,pH,SST mg/L,T_Amb ºC,T_Am ºC,T_Receb °C,T_Receb ºC
0,False,False,False,True,True,False,False,True,True,False,True
1,True,True,True,False,False,True,True,True,True,False,True
2,False,False,False,True,True,False,False,True,True,False,True
3,True,True,True,False,False,True,True,True,True,False,True
4,True,True,True,False,False,True,True,True,True,True,False
5,False,False,False,True,True,False,False,True,True,True,False
6,False,False,False,True,True,False,False,True,True,True,False
7,False,True,True,False,False,True,True,True,True,True,False
8,True,True,True,False,False,True,True,True,True,False,True
9,False,False,False,True,True,False,False,True,True,False,True
10,False,False,False,True,True,False,False,True,True,False,True
11,True,True,True,False,False,True,True,True,True,False,True
12,True,True,True,False,False,True,True,True,True,False,True
13,False,False,False,True,True,False,False,True,True,True,False
14,True,True,True,False,False,True,True,True,True,False,True
15,False,False,False,True,True,False,False,True,True,True,False
16,True,True,True,False,False,True,True,True,True,False,True
17,False,False,False,True,True,False,False,True,True,False,True
18,False,False,False,True,True,False,False,True,True,False,True
19,True,True,True,False,False,True,True,True,True,False,True
20,False,False,False,True,True,False,False,True,True,False,True
21,True,True,True,False,False,True,True,True,True,False,True
22,True,True,True,False,False,True,True,True,True,False,True
23,False,False,False,True,True,False,False,True,True,False,True
24,False,False,False,True,True,False,False,True,True,False,True
25,True,True,True,False,False,True,True,True,True,False,True
26,False,False,False,True,True,False,False,True,True,False,True
27,True,True,True,False,False,True,True,True,True,False,True
28,False,False,False,False,True,False,False,True,True,False,True
29,True,True,True,False,False,True,True,True,True,False,True
30,False,False,False,False,True,False,False,True,True,False,True
31,True,True,True,False,False,True,True,True,True,False,True