In [8]:
import pandas as pd
from pyproj import Proj, transform
import pyproj
import numpy as np

In [9]:
resultado = pd.read_excel("Resultado.xlsx")
resultado

,Matrícula,Categoria de serviço,Data de Solicitação,Endereço,Bairro,Número,Latitude,Longitude,x,y,Localização
0,NaN,Vazamento,02/01/2023 08:36:00,Rua Mal. Castelo Branco,Bracinho,NaN,7.074743e+06,693005.217413,-26.434517,-49.064493,"Rua Marechal Castelo Branco, Centro Sul, Schro..."
1,NaN,Vazamento,06/01/2023 08:19:00,Rua Barao Do Rio Branco,Centro Leste,NaN,7.079385e+06,692995.054867,-26.392632,-49.065294,"Rua Barão do Rio Branco, Centro Leste, Schroed..."
2,NaN,Vazamento,10/01/2023 10:08:00,Rua Guilherme Piske,Centro Norte,NaN,7.078325e+06,691093.114741,-26.402450,-49.084194,"Rua Guilherme Piske, Centro Norte, Schroeder, ..."
3,NaN,Vazamento,10/01/2023 14:36:00,Rua Henrique Ziebel,Rio Hern,NaN,7.075769e+06,693307.762184,-26.425218,-49.061615,"Rua Henrique Ziebel, Rio Hern, Schroeder, Regi..."
4,NaN,Vazamento,16/01/2023 13:33:00,Rua Jorge Lacerda,Centro Norte,NaN,7.079241e+06,691187.500558,-26.394173,-49.083384,"Rua Jorge Lacerda, Sossego, Schroeder, Região ..."
...,...,...,...,...,...,...,...,...,...,...,...
68,1365896-4,Falta de água,25/05/2023 15:46:00,Rua 573- Veronica Welter 156 - Schroeder I,Schroeder I,NaN,NaN,NaN,-26.451996,-49.024418,NaN
69,1369024-8,Falta de água,19/06/2023 15:10:00,Rua Santa. Catarina 15 - Braco Do Sul,Braco do Sul,NaN,7.079338e+06,691265.804666,-26.393289,-49.082614,"Rua Santa Catarina, Sossego, Schroeder, Região..."
70,801221-0,Falta de água,30/06/2023 10:13:00,Rua Duque De Caxias 381 - Centro Norte,Centro Norte,NaN,7.078714e+06,690998.662427,-26.398955,-49.085198,"Rua Duque de Caxias, Centro Norte, Schroeder, ..."
71,1354221-4,Falta de água,08/09/2023 14:21:00,Rua Pres. Costa E Silva 1291 - Rio Hern,Rio Hern,NaN,NaN,NaN,-26.419859,-49.057511,NaN
72,1368570-8,Falta de água,28/11/2023 14:08:00,Rua Mario Bagatolli 1015 - Schroeder I . - Un...,Schroeder I .,NaN,NaN,NaN,-26.420218,-49.061948,NaN

In [12]:
import pandas as pd
import pyproj

# Assuming 'resultado' is a pandas DataFrame with columns 'Latitude', 'Longitude', 'x', and 'y'
transformer = pyproj.Transformer.from_crs("epsg:4326", "epsg:32722", always_xy=True)

# Check if any values in the 'Latitude' column are NaN
if resultado['Latitude'].isna().any():
    # Apply the coordinate transformation and assign the results to 'Latitude' and 'Longitude'
    resultado['Longitude'], resultado['Latitude'] = zip(*resultado.apply(lambda row: transformer.transform(row['y'], row['x']), axis=1))

# Display the updated 'resultado' DataFrame
print(resultado)

    Matrícula Categoria de serviço  Data de Solicitação  \
0         NaN            Vazamento  02/01/2023 08:36:00
1         NaN            Vazamento  06/01/2023 08:19:00
2         NaN            Vazamento  10/01/2023 10:08:00
3         NaN            Vazamento  10/01/2023 14:36:00
4         NaN            Vazamento  16/01/2023 13:33:00
..        ...                  ...                  ...
68  1365896-4        Falta de água  25/05/2023 15:46:00
69  1369024-8        Falta de água  19/06/2023 15:10:00
70   801221-0        Falta de água  30/06/2023 10:13:00
71  1354221-4        Falta de água  08/09/2023 14:21:00
72  1368570-8        Falta de água  28/11/2023 14:08:00

                                             Endereço          Bairro  Número  \
0                            Rua  Mal. Castelo Branco        Bracinho     NaN
1                             Rua Barao Do Rio Branco    Centro Leste     NaN
2                                 Rua Guilherme Piske    Centro Norte     NaN
3                                 Rua Henrique Ziebel        Rio Hern     NaN
4                                   Rua Jorge Lacerda    Centro Norte     NaN
..                                                ...             ...     ...
68        Rua 573- Veronica Welter 156 - Schroeder I      Schroeder I     NaN
69             Rua Santa. Catarina 15 - Braco Do Sul     Braco do Sul     NaN
70            Rua Duque De Caxias 381 - Centro Norte     Centro Norte     NaN
71           Rua Pres. Costa E Silva 1291 - Rio Hern         Rio Hern     NaN
72  Rua Mario Bagatolli 1015 - Schroeder  I . - Un...  Schroeder  I .     NaN

        Latitude      Longitude          x          y  \
0   7.074743e+06  693005.217413 -26.434517 -49.064493
1   7.079385e+06  692995.054867 -26.392632 -49.065294
2   7.078325e+06  691093.114741 -26.402450 -49.084194
3   7.075769e+06  693307.762184 -26.425218 -49.061615
4   7.079241e+06  691187.500558 -26.394173 -49.083384
..           ...            ...        ...        ...
68  7.072746e+06  696972.617068 -26.451996 -49.024418
69  7.079338e+06  691265.804666 -26.393289 -49.082614
70  7.078714e+06  690998.662427 -26.398955 -49.085198
71  7.076357e+06  693726.080551 -26.419859 -49.057511
72  7.076323e+06  693282.860369 -26.420218 -49.061948

                                          Localização
0   Rua Marechal Castelo Branco, Centro Sul, Schro...
1   Rua Barão do Rio Branco, Centro Leste, Schroed...
2   Rua Guilherme Piske, Centro Norte, Schroeder, ...
3   Rua Henrique Ziebel, Rio Hern, Schroeder, Regi...
4   Rua Jorge Lacerda, Sossego, Schroeder, Região ...
..                                                ...
68                                                NaN
69  Rua Santa Catarina, Sossego, Schroeder, Região...
70  Rua Duque de Caxias, Centro Norte, Schroeder, ...
71                                                NaN
72                                                NaN

[73 rows x 11 columns]

In [13]:
display(resultado)

,Matrícula,Categoria de serviço,Data de Solicitação,Endereço,Bairro,Número,Latitude,Longitude,x,y,Localização
0,NaN,Vazamento,02/01/2023 08:36:00,Rua Mal. Castelo Branco,Bracinho,NaN,7.074743e+06,693005.217413,-26.434517,-49.064493,"Rua Marechal Castelo Branco, Centro Sul, Schro..."
1,NaN,Vazamento,06/01/2023 08:19:00,Rua Barao Do Rio Branco,Centro Leste,NaN,7.079385e+06,692995.054867,-26.392632,-49.065294,"Rua Barão do Rio Branco, Centro Leste, Schroed..."
2,NaN,Vazamento,10/01/2023 10:08:00,Rua Guilherme Piske,Centro Norte,NaN,7.078325e+06,691093.114741,-26.402450,-49.084194,"Rua Guilherme Piske, Centro Norte, Schroeder, ..."
3,NaN,Vazamento,10/01/2023 14:36:00,Rua Henrique Ziebel,Rio Hern,NaN,7.075769e+06,693307.762184,-26.425218,-49.061615,"Rua Henrique Ziebel, Rio Hern, Schroeder, Regi..."
4,NaN,Vazamento,16/01/2023 13:33:00,Rua Jorge Lacerda,Centro Norte,NaN,7.079241e+06,691187.500558,-26.394173,-49.083384,"Rua Jorge Lacerda, Sossego, Schroeder, Região ..."
...,...,...,...,...,...,...,...,...,...,...,...
68,1365896-4,Falta de água,25/05/2023 15:46:00,Rua 573- Veronica Welter 156 - Schroeder I,Schroeder I,NaN,7.072746e+06,696972.617068,-26.451996,-49.024418,NaN
69,1369024-8,Falta de água,19/06/2023 15:10:00,Rua Santa. Catarina 15 - Braco Do Sul,Braco do Sul,NaN,7.079338e+06,691265.804666,-26.393289,-49.082614,"Rua Santa Catarina, Sossego, Schroeder, Região..."
70,801221-0,Falta de água,30/06/2023 10:13:00,Rua Duque De Caxias 381 - Centro Norte,Centro Norte,NaN,7.078714e+06,690998.662427,-26.398955,-49.085198,"Rua Duque de Caxias, Centro Norte, Schroeder, ..."
71,1354221-4,Falta de água,08/09/2023 14:21:00,Rua Pres. Costa E Silva 1291 - Rio Hern,Rio Hern,NaN,7.076357e+06,693726.080551,-26.419859,-49.057511,NaN
72,1368570-8,Falta de água,28/11/2023 14:08:00,Rua Mario Bagatolli 1015 - Schroeder I . - Un...,Schroeder I .,NaN,7.076323e+06,693282.860369,-26.420218,-49.061948,NaN

In [15]:
resultado.to_csv("Resultado.csv")